# docker-compose.yml
name: rollthedice

services:
  app:
    build: .
    container_name: rollthedice
    restart: unless-stopped
    ports:
      - "8000:8000"         # lokal erreichbar unter http://localhost:8000
    volumes:
      - ./data:/app/data    # behält Leaderboard/Stats persistent


# git clone https://github.com/Maetran/RollTheDice.git
# cd RollTheDice
# docker compose up -d --build