"""Paired German/English reminder copy; each game has its own full rotation."""

REMINDER_COPY = {
    "zilch": (
        ("Am Stammtisch ist noch ein Platzerl frei. Pack die Würfel aus, die 10’000 warten!",
         "There's a seat at the Zilch table. Get your dice out — 10,000 points are waiting!"),
        ("Servus, Würfelwirt! Heute wird nicht lang g'redt, heute wird gezilcht.",
         "Evening, dice landlord! Less pub talk, more Zilch tonight."),
        ("Dein Würfelbecher setzt Staub an. Das lassen wir am Zilch-Stammtisch nicht durchgehen!",
         "Your dice cup is gathering dust. We can't have that at the Zilch table!"),
        ("Sechs Würfel, ein frecher Plan. Komm an den Tisch und zeig, was dein Zilch kann!",
         "Six dice, one cheeky plan. Pull up a chair and show us your Zilch game!"),
        ("Heisse Würfel statt kalte Füsse: Eine Runde Zilch geht sich aus, oder?",
         "Hot Dice, not cold feet. Surely there's room for a round of Zilch?"),
        ("Der Stammtisch tagt. Tagesordnung: würfeln, sichern, charmant angeben.",
         "The Zilch table is in session. Agenda: roll, bank, brag with charm."),
        ("Die 10’000 stehen auf der Karte. Bestell dir eine Runde Zilch!",
         "10,000 points are on the menu. Order yourself a round of Zilch!"),
        ("Nur noch ein Wurf? Diesen Satz kennt hier jeder. Komm wieder an den Zilch-Tisch!",
         "Just one more roll? We all know that line. Come back to the Zilch table!"),
        ("Dein Platz am Würfeltisch bleibt nicht ewig warm. Zilch-Runde mit netten Leuten?",
         "Your seat at the dice table won't stay warm forever. Fancy some Zilch and good company?"),
        ("Grosse Sprüche zählen hier null Punkte. Würfel raus, Zilch an!",
         "Big talk scores zero here. Dice out, Zilch on!"),
        ("Wirtshausweisheit: Wer nie sichert, hat später viel zu erzählen. Testen wir's bei Zilch?",
         "Pub wisdom: never bank and you'll have a story to tell. Test the theory in Zilch?"),
        ("Heute schon gezilcht? Der Punkteblock schaut drein wie ein leerer Stammtisch.",
         "Played Zilch today? Your score sheet looks as lonely as an empty pub table."),
        ("Die Einsen wollen raus, die Fünfen auch. Lass die Bande bei Zilch auf den Tisch!",
         "The ones want out. So do the fives. Let the gang loose on the Zilch table!"),
        ("Stammtisch statt Stillstand: Such dir Mitspieler und würfle frischen Gesprächsstoff.",
         "Pull up a chair, find some players and roll yourself a fresh Zilch story."),
        ("Dein Zilch-Rang wächst nicht vom Zuschauen. Zeit für Würfel, Punkte und ein bisserl Ruhm!",
         "Your Zilch rank won't grow by watching. Time for dice, points and a little glory!"),
        ("Der Würfelbecher hat Feierabendpläne. Du stehst drauf. Komm eine Runde zilchen!",
         "Your dice cup has evening plans. You're on the guest list. Come play Zilch!"),
        ("Ein freches Grinsen ersetzt keinen Drilling. Aber es steht dir gut am Zilch-Tisch!",
         "A cheeky grin won't replace three of a kind. But it suits you at the Zilch table!"),
        ("Auf dem Bierdeckel ist noch Platz für eine Siegesgeschichte. Schreib sie mit sechs Würfeln!",
         "There's room on that coaster for a victory story. Write yours with six Zilch dice!"),
        ("Sichern oder zocken? Die wichtigste Stammtischfrage wartet in Zilch auf dich.",
         "Bank or risk it? The table's favourite question is waiting for you in Zilch."),
        ("Die Würfel klappern schon ungeduldig. Setz dich her, heut wird gezilcht!",
         "The dice are rattling impatiently. Pull up a chair — tonight we Zilch!"),
        ("Sechs Würfel passen auf jeden Stammtisch. Dein Ehrgeiz hoffentlich auch. Zilch?",
         "Six dice fit on any pub table. Hopefully your ambition does too. Zilch?"),
        ("Ein Zilch ist kein Weltuntergang. Höchstens Stoff fürs nächste Stammtischgespräch.",
         "A Zilch isn't the end of the world. Just material for your next table-side story."),
        ("Deine Achievements liegen nicht unter dem Tisch. Die musst du dir schon erwürfeln!",
         "Your Zilch achievements aren't hiding under the table. You'll have to roll for them!"),
        ("Serviert wird heute: Zilch mit einer Prise Übermut. Nimm Platz!",
         "Tonight's special: Zilch with a pinch of mischief. Take a seat!"),
        ("Der Stammtisch braucht keine Ausreden, sondern Mitspieler. Bist dabei beim Zilchen?",
         "The table needs players, not excuses. Joining us for Zilch?"),
        ("Würfelglück kann man nicht vorbestellen. Aber bei Zilch schon mal Platz nehmen.",
         "You can't pre-order lucky dice. But you can grab a seat at the Zilch table."),
        ("Punkte aufs Papier, Schmäh an den Tisch. So schmeckt ein guter Zilch-Abend!",
         "Points on paper, banter round the table. That's a proper Zilch evening!"),
        ("Dein innerer Zocker hat reserviert. Tisch für sechs Würfel, bitte!",
         "Your inner risk-taker has booked in. A table for six dice, please!"),
        ("Hot Dice auf der Tageskarte! Ob's welche gibt, entscheidet dein nächster Zilch-Wurf.",
         "Hot Dice on the specials board! Your next Zilch roll decides what's served."),
        ("Komm her, wir zählen bis 10’000. Mit Würfeln geht das deutlich lustiger.",
         "Come on, let's count to 10,000. It's much more fun with Zilch dice."),
        ("Der Stammtisch munkelt, du hättest einen guten Lauf drauf. Zeig's den Zilch-Würfeln!",
         "Word round the table is you're due a good run. Show those Zilch dice!"),
        ("Letzte Frage vorm Würfeln: Wer sitzt mit dir am Tisch? Auf in die Zilch-Lobby!",
         "One question before we roll: who's joining your table? Head to the Zilch lobby!"),
    ),
    "zdwa": (
        ("Heute schon die Wand angezockt? Dein Punkteblock wird langsam ungeduldig.",
         "Played ZDWA today? Your score sheet is getting impatient."),
        ("Dein Highscore hat es sich bequem gemacht. Bring ihn bei ZDWA ins Schwitzen!",
         "Your high score is getting comfortable. Give it a workout in ZDWA!"),
        ("Grosse Ansage, flinke Würfel. Wer zockt heute mit dir die Wand an?",
         "Big call, quick dice. Who's joining you for ZDWA today?"),
        ("Fünf Würfel suchen jemanden mit einem frechen Plan. Wir dachten da an dich.",
         "Five dice need someone with a cheeky plan. We thought of you. ZDWA?"),
        ("Die Wand steht noch. Das können wir würfeltechnisch nicht so stehen lassen!",
         "The wall is still standing. Those ZDWA dice have something to say about that!"),
        ("Deine Ehrenberg-Marken vermehren sich nicht durchs Anschauen. Eine Runde ZDWA?",
         "Staring at your Ehrenberg Tokens won't multiply them. Fancy a round of ZDWA?"),
        ("Heute schon gross aufgespielt? Dein nächstes Full House könnte in ZDWA warten.",
         "Made a big play today? Your next Full House could be waiting in ZDWA."),
        ("Weniger Daumen-Sport, mehr Würfel-Sport. Die ZDWA-Lobby ist bereit!",
         "Less thumb-scrolling, more dice-rolling. The ZDWA lobby is ready!"),
        ("Dein Punkteblock hat freie Felder und grosse Erwartungen. Enttäusch das Papier nicht!",
         "Your ZDWA score sheet has empty boxes and big dreams. Don't let the paper down!"),
        ("Ansagen kann jeder. Die Würfel haben das letzte Wort. Zeit für ZDWA!",
         "Anyone can make a bold call. The dice get the last word. Time for ZDWA!"),
        ("Ein bisschen Würfelglück, ein bisschen Grössenwahn. Klingt nach einer guten ZDWA-Runde.",
         "A little dice luck, a little wild ambition. Sounds like a great round of ZDWA."),
        ("Dein nächstes Achievement möchte nicht ewig ein Geheimnis bleiben. Zock die Wand an!",
         "Your next achievement doesn't want to stay a mystery forever. Let's play ZDWA!"),
        ("Die Würfel sind klein. Deine Pläne dürfen grösser sein. Auf in die ZDWA-Lobby!",
         "The dice are small. Your plans don't have to be. Head to the ZDWA lobby!"),
        ("Full House klingt nach Gesellschaft. Such dir welche und zock die Wand an!",
         "Full House sounds like good company. Find some and fire up ZDWA!"),
        ("Dein Rangabzeichen kann noch ein bisschen Glanz vertragen. Würfeln wir dran?",
         "Your rank badge could use a little more sparkle. Shall we roll for it in ZDWA?"),
        ("Eine Strasse baut sich nicht von allein. Zum Glück brauchst du in ZDWA nur Würfel.",
         "Straights don't build themselves. Luckily, all you need in ZDWA is dice."),
        ("Die Wand hat heute noch keinen frechen Spruch von dir gehört. Wird Zeit für ZDWA!",
         "The wall hasn't heard your cheeky banter today. Time for ZDWA!"),
        ("Fünf Würfel, nette Leute, ein ehrgeiziger Punkteblock. Dein ZDWA-Abend kann kommen.",
         "Five dice, good company, an ambitious score sheet. Your ZDWA evening awaits."),
        ("Dein Rekord tut so, als wäre er unantastbar. Zeig ihm bei ZDWA, was Sache ist!",
         "Your record thinks it's untouchable. Show it who's boss in ZDWA!"),
        ("Die Würfel haben keine Ausrede parat. Du etwa? Komm die Wand anzocken!",
         "The dice haven't got an excuse. Have you? Come play ZDWA!"),
        ("Ein Poker würde deinem Punkteblock gut stehen. Frag doch mal die ZDWA-Würfel!",
         "Four of a kind would look good on your score sheet. Ask the ZDWA dice!"),
        ("Zocken, schnacken, Erfolge knacken. Die ZDWA-Lobby wartet auf deinen Auftritt!",
         "Roll dice, chat, crack achievements. The ZDWA lobby awaits your entrance!"),
        ("Gross denken, clever eintragen. Heute ist ein guter Tag, die Wand anzuzocken.",
         "Think big, score smart. Today's a good day for ZDWA."),
        ("Die nächste Runde hat noch keinen Helden. Bewirb dich mit fünf Würfeln bei ZDWA!",
         "The next round hasn't found its hero. Apply with five dice in ZDWA!"),
        ("Dein Würfelarm ist ausgeruht. Dein Ehrgeiz hoffentlich nicht. Eine Runde ZDWA?",
         "Your rolling arm is rested. Hopefully your ambition isn't. A round of ZDWA?"),
        ("Der Punkteblock ist geduldig. Deine Mitspieler vielleicht weniger. Schau in ZDWA vorbei!",
         "Your score sheet is patient. Your fellow players might not be. Drop into ZDWA!"),
        ("Ein frecher Plan für heute: Mitspieler finden, Würfel rollen, Wand anzocken.",
         "A cheeky plan for tonight: find players, roll dice, play ZDWA."),
        ("Deine nächste Glanzleistung passt in ein kleines Feld. Mach den ZDWA-Block stolz!",
         "Your next moment of glory fits in one little box. Make your ZDWA sheet proud!"),
        ("Die Wand fordert Revanche. Oder Gesellschaft. Mit einer Runde ZDWA geht beides.",
         "The wall wants a rematch. Or company. A round of ZDWA covers both."),
        ("Glück muss man auch mal an den Würfeln packen. Komm in die ZDWA-Lobby!",
         "Sometimes you have to grab luck by the dice. Come to the ZDWA lobby!"),
        ("Ein paar Marken mehr, ein paar gute Sprüche dazu. Wie wär's mit ZDWA?",
         "A few more Tokens, a little more banter. How about some ZDWA?"),
        ("Dein Feierabend kann fünf Würfel vertragen. Zockst du heute noch die Wand an?",
         "Your evening could use five dice. Up for some ZDWA today?"),
    ),
}
